
site_name: "NSM: Null-space optimization for neural networks"
site_author: "Hrittik Roy"
site_url: https://h-roy.github.io/deep-nsm/
theme:
  name: material
  features:
    - content.code.annotate  # Allows for code annotations
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
repo_url: https://github.com/h-roy/deep-nsm
repo_name: h-roy/deep-nsm

nav:
  - 'User Guide': 'index.md'
  - 'API Reference': 'api.md'
# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src] # Tell mkdocstrings to look for code in the 'src' directory
          options:
            show_root_heading: yes
            show_source: true # Optionally show the source code for functions
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
